server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: patient-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/patients/**, /api/medical-histories/**, /api/diagnoses/**
        - id: appointment-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/appointments/**, /api/doctors/**, /api/payments/**